### ISSUE TITLE
library not working due to phantom NETWORK_ERR Exception

### ISSUE THREAD

**Issue by stukennedy** [IonicaBizau/phantom-jquery#6]
this looks like the perfect library for test automation ... only problem is it's not working for me.

```
phantom stdout: NETWORK_ERR: XMLHttpRequest Exception 101: A network error occurred in synchronous requests.
```

I think the issue was introduced with Phantom v2 (https://github.com/amir20/phantomjs-node/issues/345)
Is there any way to get this to work? Can you depend on v1.9.8 instead?

**Comment by IonicaBizau** [comment]
We should disable the `web-security` option. That should be happening [here](https://github.com/IonicaBizau/phantom-jquery/blob/d57f8a1b95f44f7690a7521db452a9372d200497/lib/index.js#L51).

**Comment by IonicaBizau** [comment]
Which will be passed to `ghosty`: https://github.com/IonicaBizau/ghosty/blob/5946d61a580df2d0a09343a0f1129f58dd81b797/lib/index.js#L23-L36

/ref http://stackoverflow.com/a/15913778/1420197
